services:
  backend:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_DATABASE: admin
      DB_USERNAME: root
      DB_PASSWORD: root
    expose:
      - "9000"
    volumes:
      - ./:/var/www/html/
    depends_on:
      - db
    networks:
      - app

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8000:80"
    volumes:
        - ./:/var/www/html/
    depends_on:
      - backend
    networks:
        - app

  db:
    container_name: admin_db
    platform: linux/x86_64
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
    - "3306:3306"
    networks:
      - app
networks:
  app:
